[env]
RUST_LOG = { value = "debug", force = true }
RUST_BACKTRACE = { value = "full", force = true }
DYLD_LIBRARY_PATH = { value = "libtorch/lib:$DYLD_LIBRARY_PATH", force = true, relative = true }
LIBTORCH = { value = "libtorch", force = true, relative = true }
LIBTORCH_INCLUDE = { value = "libtorch", force = true, relative = true }
LIBTORCH_LIB = { value = "libtorch", force = true, relative = true }

[target.x86_64-unknown-linux-gnu]
rustflags = [
    "-C",
    "link-arg=-Wl,--allow-shlib-undefined",
    "-C",
    "link-arg=-fno-lto",
]
